package com.iut.banque.test.selenium;
// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.edge.EdgeDriver;

import java.util.HashMap;
import java.util.Map;
public class TestSelenium {
    private WebDriver driver;
    protected Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.edge.driver", "src\\main\\resources\\msedgedriver.exe");
        driver = new EdgeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void imageTest() {
        // Ouvrir la page
        driver.get("http://localhost:8083/");

        // Ajuster la taille de la fenêtre
        driver.manage().window().setSize(new Dimension(1050, 1052));

        // Vérifier que l'image est bien présente
        WebElement image = driver.findElement(By.cssSelector("img"));
        Assert.assertNotNull(image);

        // Vérifier que l'image est affichée
        Assert.assertTrue(image.isDisplayed());

        // Vérifier que l'image a un src valide
        String src = image.getAttribute("src");
        Assert.assertNotNull(src);
        Assert.assertFalse(src.isEmpty());

        // Vérifier que l'image a une taille correcte
        Dimension size = image.getSize();
        Assert.assertTrue(size.getWidth() > 0);
        Assert.assertTrue(size.getHeight() > 0);
    }

    @Test
    public void connectUsertest() {
        // Test name: ConnectUsertest
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://localhost:8083/");
        // 2 | setWindowSize | 1050x1052 |
        driver.manage().window().setSize(new Dimension(1050, 1052));
        // 3 | click | linkText=Page de Login |
        driver.findElement(By.linkText("Page de Login")).click();
        // 4 | click | id=controller_Connect_login_action_userCde |
        driver.findElement(By.id("controller_Connect_login_action_userCde")).click();
        // 5 | type | id=controller_Connect_login_action_userCde | client1
        driver.findElement(By.id("controller_Connect_login_action_userCde")).sendKeys("client1");
        // 6 | click | id=controller_Connect_login_action_userPwd |
        driver.findElement(By.id("controller_Connect_login_action_userPwd")).click();
        // 7 | type | id=controller_Connect_login_action_userPwd | clientpass1
        driver.findElement(By.id("controller_Connect_login_action_userPwd")).sendKeys("clientpass1");
        driver.findElement(By.id("controller_Connect_login_action_userPwd")).sendKeys(Keys.ENTER);
        WebElement h1Element = driver.findElement(By.cssSelector("h1"));
        Assert.assertEquals("Tableau de bord", h1Element.getText());
        WebElement btnLogoutElement = driver.findElement(By.name("Retour"));
        Assert.assertEquals("Logout", btnLogoutElement.getAttribute("value"));
    }
}
